# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

include: "rules/common.smk"
include: "rules/pemapping.smk"
include: "rules/semapping.smk"
include: "rules/peakcalling.smk"
include: "rules/plots.smk"
include: "rules/trackhub.smk"

species = config.get("species", "mm10")
rule all:
    input:
        heatmaps=expand("results/plots/%s/joined/all_{plottype}.png" % species, plottype=("average", "heat", "tss")),
        trackhub=f"results/trackhub/{species}/trackDb.txt",
        domains=expand(f"results/{species}/domains/{{combo}}.bed", combo=[c for c in combos if not c.lower().endswith("input")]),

        # multimap=expand("results/mm10/multimapped_dedup_pe/{sample}.sam.gz", sample=samples.index)

include: "rules/other.smk"
