# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

include: "rules/common.smk"
include: "rules/pemapping.smk"
include: "rules/semapping.smk"
include: "rules/peakcalling.smk"
include: "rules/plots.smk"
include: "rules/trackhub.smk"
include: "rules/sra.smk"

rule all:
    input:
        heatmaps=expand("results/plots/joined/all_{plottype}.png", plottype=("average", "heat", "tss")),
        trackhub=expand("results/trackhub/hub.txt")

include: "rules/other.smk"
